import type { CanvasElement } from "@/lib/types/canvas-elements";

export interface LayoutTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  width: number;
  height: number;
  elements: CanvasElement[];
}

/** Replace all element IDs with fresh UUIDs when cloning a template */
export function cloneTemplateElements(
  elements: CanvasElement[]
): CanvasElement[] {
  return elements.map((el) => ({ ...el, id: crypto.randomUUID() }));
}

export const LAYOUT_TEMPLATES: LayoutTemplate[] = [
  // ── Ember ──────────────────────────────────────────────────
  {
    id: "ember",
    name: "Ember",
    description: "Warm gradient card with glowing accents.",
    category: "General",
    width: 750,
    height: 1050,
    elements: [
      // Background gradient
      {
        id: "t1-1",
        type: "shape",
        x: 0,
        y: 0,
        width: 750,
        height: 1050,
        z_index: 0,
        shape_type: "rectangle",
        fill_type: "linear",
        gradient: {
          type: "linear",
          angle: 160,
          stops: [
            { color: "#1a0a00", position: 0 },
            { color: "#3d1308", position: 40 },
            { color: "#7c1d05", position: 100 },
          ],
        },
      },
      // Top accent bar
      {
        id: "t1-2",
        type: "shape",
        x: 0,
        y: 0,
        width: 750,
        height: 6,
        z_index: 3,
        shape_type: "rectangle",
        fill_type: "linear",
        gradient: {
          type: "linear",
          angle: 90,
          stops: [
            { color: "#ff6b35", position: 0 },
            { color: "#fbbf24", position: 50 },
            { color: "#ff6b35", position: 100 },
          ],
        },
      },
      // Title
      {
        id: "t1-3",
        type: "text",
        x: 50,
        y: 40,
        width: 650,
        height: 70,
        z_index: 2,
        font_size: 44,
        font_weight: "bold",
        text_align: "left",
        vertical_align: "middle",
        color: "#fbbf24",
        overflow: "truncate",
        static_text: "Card Title",
        text_shadow: { color: "rgba(251,191,36,0.4)", offset_x: 0, offset_y: 0, blur: 12 },
      },
      // Divider line
      {
        id: "t1-4",
        type: "shape",
        x: 50,
        y: 125,
        width: 200,
        height: 3,
        z_index: 2,
        shape_type: "rectangle",
        fill_type: "linear",
        gradient: {
          type: "linear",
          angle: 90,
          stops: [
            { color: "#ff6b35", position: 0 },
            { color: "rgba(255,107,53,0)", position: 100 },
          ],
        },
      },
      // Art frame
      {
        id: "t1-5",
        type: "shape",
        x: 40,
        y: 150,
        width: 670,
        height: 440,
        z_index: 1,
        shape_type: "rectangle",
        fill: "rgba(0,0,0,0.3)",
        border_radius: 12,
        stroke: "#ff6b35",
        stroke_width: 1,
      },
      {
        id: "t1-6",
        type: "image",
        x: 44,
        y: 154,
        width: 662,
        height: 432,
        z_index: 2,
        object_fit: "cover",
        border_radius: 10,
      },
      // Body text area
      {
        id: "t1-7",
        type: "shape",
        x: 40,
        y: 620,
        width: 670,
        height: 320,
        z_index: 1,
        shape_type: "rectangle",
        fill: "rgba(0,0,0,0.35)",
        border_radius: 12,
        stroke: "rgba(255,107,53,0.3)",
        stroke_width: 1,
      },
      {
        id: "t1-8",
        type: "text",
        x: 60,
        y: 640,
        width: 630,
        height: 280,
        z_index: 2,
        font_size: 22,
        font_weight: "normal",
        text_align: "left",
        vertical_align: "top",
        color: "#e8c9a0",
        overflow: "wrap",
        static_text: "Card description and rules text. Describe abilities, effects, and flavor text for this card.",
      },
      // Footer
      {
        id: "t1-9",
        type: "text",
        x: 50,
        y: 970,
        width: 650,
        height: 40,
        z_index: 2,
        font_size: 16,
        font_weight: "normal",
        text_align: "right",
        vertical_align: "middle",
        color: "#a0522d",
        overflow: "truncate",
        static_text: "Collection Name",
      },
    ],
  },

  // ── Frost ──────────────────────────────────────────────────
  {
    id: "frost",
    name: "Frost",
    description: "Cool blue tones with icy highlights.",
    category: "General",
    width: 750,
    height: 1050,
    elements: [
      // Background
      {
        id: "t2-1",
        type: "shape",
        x: 0,
        y: 0,
        width: 750,
        height: 1050,
        z_index: 0,
        shape_type: "rectangle",
        fill_type: "radial",
        gradient: {
          type: "radial",
          stops: [
            { color: "#1e3a5f", position: 0 },
            { color: "#0a1628", position: 100 },
          ],
        },
      },
      // Decorative ellipse glow (top-right)
      {
        id: "t2-2",
        type: "shape",
        x: 400,
        y: -80,
        width: 500,
        height: 400,
        z_index: 1,
        shape_type: "ellipse",
        fill_type: "radial",
        gradient: {
          type: "radial",
          stops: [
            { color: "rgba(56,189,248,0.15)", position: 0 },
            { color: "rgba(56,189,248,0)", position: 100 },
          ],
        },
      },
      // Inner border
      {
        id: "t2-3",
        type: "shape",
        x: 20,
        y: 20,
        width: 710,
        height: 1010,
        z_index: 1,
        shape_type: "rectangle",
        fill: undefined,
        stroke: "rgba(56,189,248,0.25)",
        stroke_width: 1,
        border_radius: 16,
      },
      // Title
      {
        id: "t2-4",
        type: "text",
        x: 50,
        y: 40,
        width: 540,
        height: 60,
        z_index: 2,
        font_size: 36,
        font_weight: "bold",
        text_align: "left",
        vertical_align: "middle",
        color: "#e0f2fe",
        overflow: "truncate",
        static_text: "Card Name",
        text_shadow: { color: "rgba(56,189,248,0.5)", offset_x: 0, offset_y: 0, blur: 10 },
      },
      // Cost circle
      {
        id: "t2-5",
        type: "shape",
        x: 630,
        y: 35,
        width: 70,
        height: 70,
        z_index: 2,
        shape_type: "ellipse",
        fill_type: "radial",
        gradient: {
          type: "radial",
          stops: [
            { color: "#38bdf8", position: 0 },
            { color: "#0284c7", position: 100 },
          ],
        },
      },
      {
        id: "t2-6",
        type: "text",
        x: 630,
        y: 35,
        width: 70,
        height: 70,
        z_index: 3,
        font_size: 32,
        font_weight: "bold",
        text_align: "center",
        vertical_align: "middle",
        color: "#ffffff",
        overflow: "truncate",
        static_text: "3",
      },
      // Art frame
      {
        id: "t2-7",
        type: "image",
        x: 40,
        y: 120,
        width: 670,
        height: 400,
        z_index: 2,
        object_fit: "cover",
        border_radius: 12,
      },
      // Frost overlay on art bottom
      {
        id: "t2-8",
        type: "shape",
        x: 40,
        y: 400,
        width: 670,
        height: 120,
        z_index: 3,
        shape_type: "rectangle",
        fill_type: "linear",
        gradient: {
          type: "linear",
          angle: 180,
          stops: [
            { color: "rgba(10,22,40,0)", position: 0 },
            { color: "rgba(10,22,40,0.9)", position: 100 },
          ],
        },
        border_radius: 12,
      },
      // Type line
      {
        id: "t2-9",
        type: "text",
        x: 50,
        y: 530,
        width: 650,
        height: 35,
        z_index: 2,
        font_size: 16,
        font_weight: "normal",
        text_align: "left",
        vertical_align: "middle",
        color: "#38bdf8",
        overflow: "truncate",
        static_text: "Creature — Ice Elemental",
        letter_spacing: 2,
      },
      // Rules box
      {
        id: "t2-10",
        type: "shape",
        x: 40,
        y: 575,
        width: 670,
        height: 340,
        z_index: 1,
        shape_type: "rectangle",
        fill: "rgba(14,30,52,0.7)",
        border_radius: 12,
        stroke: "rgba(56,189,248,0.15)",
        stroke_width: 1,
      },
      {
        id: "t2-11",
        type: "text",
        x: 60,
        y: 595,
        width: 630,
        height: 300,
        z_index: 2,
        font_size: 20,
        font_weight: "normal",
        text_align: "left",
        vertical_align: "top",
        color: "#bae6fd",
        overflow: "wrap",
        static_text: "Rules text goes here. Describe what this card does, its abilities, and interactions.",
      },
      // Stats bar
      {
        id: "t2-12",
        type: "shape",
        x: 520,
        y: 940,
        width: 190,
        height: 55,
        z_index: 2,
        shape_type: "rectangle",
        fill_type: "linear",
        gradient: {
          type: "linear",
          angle: 90,
          stops: [
            { color: "#0284c7", position: 0 },
            { color: "#38bdf8", position: 100 },
          ],
        },
        border_radius: 28,
      },
      {
        id: "t2-13",
        type: "text",
        x: 520,
        y: 940,
        width: 190,
        height: 55,
        z_index: 3,
        font_size: 26,
        font_weight: "bold",
        text_align: "center",
        vertical_align: "middle",
        color: "#ffffff",
        overflow: "truncate",
        static_text: "4 / 5",
      },
    ],
  },

  // ── Verdant ────────────────────────────────────────────────
  {
    id: "verdant",
    name: "Verdant",
    description: "Rich greens and gold for nature-themed cards.",
    category: "General",
    width: 750,
    height: 1050,
    elements: [
      // Background
      {
        id: "t3-1",
        type: "shape",
        x: 0,
        y: 0,
        width: 750,
        height: 1050,
        z_index: 0,
        shape_type: "rectangle",
        fill_type: "linear",
        gradient: {
          type: "linear",
          angle: 170,
          stops: [
            { color: "#052e16", position: 0 },
            { color: "#14532d", position: 50 },
            { color: "#052e16", position: 100 },
          ],
        },
      },
      // Gold top border
      {
        id: "t3-2",
        type: "shape",
        x: 30,
        y: 25,
        width: 690,
        height: 3,
        z_index: 2,
        shape_type: "rectangle",
        fill_type: "linear",
        gradient: {
          type: "linear",
          angle: 90,
          stops: [
            { color: "rgba(217,170,62,0)", position: 0 },
            { color: "#d9aa3e", position: 50 },
            { color: "rgba(217,170,62,0)", position: 100 },
          ],
        },
      },
      // Title
      {
        id: "t3-3",
        type: "text",
        x: 50,
        y: 40,
        width: 550,
        height: 65,
        z_index: 2,
        font_size: 38,
        font_weight: "bold",
        text_align: "left",
        vertical_align: "middle",
        color: "#d9aa3e",
        overflow: "truncate",
        static_text: "Card Name",
        text_shadow: { color: "rgba(217,170,62,0.3)", offset_x: 0, offset_y: 2, blur: 8 },
      },
      // Cost badge
      {
        id: "t3-4",
        type: "shape",
        x: 630,
        y: 38,
        width: 75,
        height: 55,
        z_index: 2,
        shape_type: "rectangle",
        fill: "#d9aa3e",
        border_radius: 10,
        box_shadow: { color: "rgba(217,170,62,0.4)", offset_x: 0, offset_y: 2, blur: 10, spread: 0 },
      },
      {
        id: "t3-5",
        type: "text",
        x: 630,
        y: 38,
        width: 75,
        height: 55,
        z_index: 3,
        font_size: 30,
        font_weight: "bold",
        text_align: "center",
        vertical_align: "middle",
        color: "#052e16",
        overflow: "truncate",
        static_text: "2",
      },
      // Art area with border
      {
        id: "t3-6",
        type: "shape",
        x: 35,
        y: 120,
        width: 680,
        height: 420,
        z_index: 1,
        shape_type: "rectangle",
        fill: "#0a1f0f",
        border_radius: 8,
        stroke: "#d9aa3e",
        stroke_width: 2,
      },
      {
        id: "t3-7",
        type: "image",
        x: 40,
        y: 125,
        width: 670,
        height: 410,
        z_index: 2,
        object_fit: "cover",
        border_radius: 6,
      },
      // Type ribbon
      {
        id: "t3-8",
        type: "shape",
        x: 35,
        y: 555,
        width: 680,
        height: 42,
        z_index: 2,
        shape_type: "rectangle",
        fill_type: "linear",
        gradient: {
          type: "linear",
          angle: 90,
          stops: [
            { color: "#d9aa3e", position: 0 },
            { color: "#b8860b", position: 100 },
          ],
        },
        border_radius: 0,
      },
      {
        id: "t3-9",
        type: "text",
        x: 50,
        y: 555,
        width: 650,
        height: 42,
        z_index: 3,
        font_size: 16,
        font_weight: "bold",
        text_align: "center",
        vertical_align: "middle",
        color: "#052e16",
        overflow: "truncate",
        static_text: "Creature — Forest Guardian",
        letter_spacing: 1,
      },
      // Text box
      {
        id: "t3-10",
        type: "shape",
        x: 35,
        y: 612,
        width: 680,
        height: 340,
        z_index: 1,
        shape_type: "rectangle",
        fill: "rgba(5,46,22,0.6)",
        border_radius: 8,
        stroke: "rgba(217,170,62,0.4)",
        stroke_width: 1,
      },
      {
        id: "t3-11",
        type: "text",
        x: 55,
        y: 630,
        width: 640,
        height: 300,
        z_index: 2,
        font_size: 20,
        font_weight: "normal",
        text_align: "left",
        vertical_align: "top",
        color: "#bbf7d0",
        overflow: "wrap",
        static_text: "Rules text goes here. Describe this card's abilities, triggered effects, and flavor text.",
      },
      // Power badge
      {
        id: "t3-12",
        type: "shape",
        x: 590,
        y: 960,
        width: 120,
        height: 55,
        z_index: 2,
        shape_type: "rectangle",
        fill: "#d9aa3e",
        border_radius: 8,
        box_shadow: { color: "rgba(217,170,62,0.3)", offset_x: 0, offset_y: 2, blur: 8, spread: 0 },
      },
      {
        id: "t3-13",
        type: "text",
        x: 590,
        y: 960,
        width: 120,
        height: 55,
        z_index: 3,
        font_size: 26,
        font_weight: "bold",
        text_align: "center",
        vertical_align: "middle",
        color: "#052e16",
        overflow: "truncate",
        static_text: "5 / 3",
      },
    ],
  },

  // ── Neon ───────────────────────────────────────────────────
  {
    id: "neon",
    name: "Neon",
    description: "Cyberpunk-inspired with vivid pink and purple.",
    category: "General",
    width: 750,
    height: 1050,
    elements: [
      // Dark background
      {
        id: "t4-1",
        type: "shape",
        x: 0,
        y: 0,
        width: 750,
        height: 1050,
        z_index: 0,
        shape_type: "rectangle",
        fill: "#0a0a0f",
      },
      // Purple glow (bottom-left)
      {
        id: "t4-2",
        type: "shape",
        x: -100,
        y: 600,
        width: 500,
        height: 500,
        z_index: 1,
        shape_type: "ellipse",
        fill_type: "radial",
        gradient: {
          type: "radial",
          stops: [
            { color: "rgba(168,85,247,0.12)", position: 0 },
            { color: "rgba(168,85,247,0)", position: 100 },
          ],
        },
      },
      // Pink glow (top-right)
      {
        id: "t4-3",
        type: "shape",
        x: 350,
        y: -50,
        width: 500,
        height: 400,
        z_index: 1,
        shape_type: "ellipse",
        fill_type: "radial",
        gradient: {
          type: "radial",
          stops: [
            { color: "rgba(236,72,153,0.12)", position: 0 },
            { color: "rgba(236,72,153,0)", position: 100 },
          ],
        },
      },
      // Neon border
      {
        id: "t4-4",
        type: "shape",
        x: 16,
        y: 16,
        width: 718,
        height: 1018,
        z_index: 2,
        shape_type: "rectangle",
        fill: undefined,
        stroke: "#ec4899",
        stroke_width: 2,
        border_radius: 20,
        box_shadow: { color: "rgba(236,72,153,0.3)", offset_x: 0, offset_y: 0, blur: 15, spread: 0 },
      },
      // Title
      {
        id: "t4-5",
        type: "text",
        x: 50,
        y: 35,
        width: 550,
        height: 60,
        z_index: 3,
        font_size: 38,
        font_weight: "bold",
        text_align: "left",
        vertical_align: "middle",
        color: "#f0abfc",
        overflow: "truncate",
        static_text: "Card Name",
        text_shadow: { color: "rgba(240,171,252,0.6)", offset_x: 0, offset_y: 0, blur: 12 },
      },
      // Cost pill
      {
        id: "t4-6",
        type: "shape",
        x: 620,
        y: 38,
        width: 90,
        height: 44,
        z_index: 3,
        shape_type: "rectangle",
        fill_type: "linear",
        gradient: {
          type: "linear",
          angle: 90,
          stops: [
            { color: "#ec4899", position: 0 },
            { color: "#a855f7", position: 100 },
          ],
        },
        border_radius: 22,
        box_shadow: { color: "rgba(236,72,153,0.4)", offset_x: 0, offset_y: 0, blur: 10, spread: 0 },
      },
      {
        id: "t4-7",
        type: "text",
        x: 620,
        y: 38,
        width: 90,
        height: 44,
        z_index: 4,
        font_size: 24,
        font_weight: "bold",
        text_align: "center",
        vertical_align: "middle",
        color: "#ffffff",
        overflow: "truncate",
        static_text: "5",
      },
      // Art area
      {
        id: "t4-8",
        type: "image",
        x: 35,
        y: 110,
        width: 680,
        height: 420,
        z_index: 2,
        object_fit: "cover",
        border_radius: 14,
      },
      // Scanline overlay on art
      {
        id: "t4-9",
        type: "shape",
        x: 35,
        y: 110,
        width: 680,
        height: 420,
        z_index: 3,
        shape_type: "rectangle",
        fill: "rgba(10,10,15,0.15)",
        border_radius: 14,
      },
      // Type line
      {
        id: "t4-10",
        type: "text",
        x: 50,
        y: 545,
        width: 650,
        height: 30,
        z_index: 3,
        font_size: 14,
        font_weight: "bold",
        text_align: "left",
        vertical_align: "middle",
        color: "#a855f7",
        overflow: "truncate",
        static_text: "PROGRAM  //  ATTACK",
        letter_spacing: 3,
      },
      // Rules box
      {
        id: "t4-11",
        type: "shape",
        x: 35,
        y: 585,
        width: 680,
        height: 340,
        z_index: 2,
        shape_type: "rectangle",
        fill: "rgba(20,20,30,0.7)",
        border_radius: 14,
        stroke: "rgba(168,85,247,0.3)",
        stroke_width: 1,
      },
      {
        id: "t4-12",
        type: "text",
        x: 55,
        y: 605,
        width: 640,
        height: 300,
        z_index: 3,
        font_size: 20,
        font_weight: "normal",
        text_align: "left",
        vertical_align: "top",
        color: "#e4e4e7",
        overflow: "wrap",
        static_text: "Card effect description. Use this space for abilities, triggers, and flavor text.",
      },
      // Stats pill
      {
        id: "t4-13",
        type: "shape",
        x: 510,
        y: 945,
        width: 195,
        height: 55,
        z_index: 3,
        shape_type: "rectangle",
        fill_type: "linear",
        gradient: {
          type: "linear",
          angle: 90,
          stops: [
            { color: "#a855f7", position: 0 },
            { color: "#ec4899", position: 100 },
          ],
        },
        border_radius: 28,
        box_shadow: { color: "rgba(168,85,247,0.4)", offset_x: 0, offset_y: 0, blur: 12, spread: 0 },
      },
      {
        id: "t4-14",
        type: "text",
        x: 510,
        y: 945,
        width: 195,
        height: 55,
        z_index: 4,
        font_size: 26,
        font_weight: "bold",
        text_align: "center",
        vertical_align: "middle",
        color: "#ffffff",
        overflow: "truncate",
        static_text: "7 / 3",
      },
    ],
  },

  // ── Regal ──────────────────────────────────────────────────
  {
    id: "regal",
    name: "Regal",
    description: "Deep purple and gold, fit for royalty.",
    category: "General",
    width: 750,
    height: 1050,
    elements: [
      // Background
      {
        id: "t5-1",
        type: "shape",
        x: 0,
        y: 0,
        width: 750,
        height: 1050,
        z_index: 0,
        shape_type: "rectangle",
        fill_type: "linear",
        gradient: {
          type: "linear",
          angle: 180,
          stops: [
            { color: "#1a0533", position: 0 },
            { color: "#2d0a4e", position: 50 },
            { color: "#1a0533", position: 100 },
          ],
        },
      },
      // Gold double border
      {
        id: "t5-2",
        type: "shape",
        x: 18,
        y: 18,
        width: 714,
        height: 1014,
        z_index: 1,
        shape_type: "rectangle",
        fill: undefined,
        stroke: "#c5a03f",
        stroke_width: 2,
        border_radius: 14,
      },
      {
        id: "t5-3",
        type: "shape",
        x: 28,
        y: 28,
        width: 694,
        height: 994,
        z_index: 1,
        shape_type: "rectangle",
        fill: undefined,
        stroke: "rgba(197,160,63,0.4)",
        stroke_width: 1,
        border_radius: 10,
      },
      // Header bar
      {
        id: "t5-4",
        type: "shape",
        x: 35,
        y: 35,
        width: 680,
        height: 70,
        z_index: 2,
        shape_type: "rectangle",
        fill_type: "linear",
        gradient: {
          type: "linear",
          angle: 90,
          stops: [
            { color: "rgba(197,160,63,0.2)", position: 0 },
            { color: "rgba(197,160,63,0.05)", position: 50 },
            { color: "rgba(197,160,63,0.2)", position: 100 },
          ],
        },
        border_radius: 8,
      },
      // Title
      {
        id: "t5-5",
        type: "text",
        x: 55,
        y: 40,
        width: 530,
        height: 60,
        z_index: 3,
        font_size: 34,
        font_weight: "bold",
        text_align: "left",
        vertical_align: "middle",
        color: "#c5a03f",
        overflow: "truncate",
        static_text: "Card Name",
        text_shadow: { color: "rgba(197,160,63,0.3)", offset_x: 0, offset_y: 1, blur: 8 },
      },
      // Cost
      {
        id: "t5-6",
        type: "shape",
        x: 630,
        y: 42,
        width: 56,
        height: 56,
        z_index: 3,
        shape_type: "ellipse",
        fill: "#c5a03f",
        box_shadow: { color: "rgba(197,160,63,0.5)", offset_x: 0, offset_y: 0, blur: 10, spread: 0 },
      },
      {
        id: "t5-7",
        type: "text",
        x: 630,
        y: 42,
        width: 56,
        height: 56,
        z_index: 4,
        font_size: 28,
        font_weight: "bold",
        text_align: "center",
        vertical_align: "middle",
        color: "#1a0533",
        overflow: "truncate",
        static_text: "4",
      },
      // Art
      {
        id: "t5-8",
        type: "shape",
        x: 35,
        y: 115,
        width: 680,
        height: 430,
        z_index: 1,
        shape_type: "rectangle",
        fill: "#110220",
        border_radius: 8,
        stroke: "rgba(197,160,63,0.5)",
        stroke_width: 1,
      },
      {
        id: "t5-9",
        type: "image",
        x: 39,
        y: 119,
        width: 672,
        height: 422,
        z_index: 2,
        object_fit: "cover",
        border_radius: 6,
      },
      // Type
      {
        id: "t5-10",
        type: "text",
        x: 50,
        y: 555,
        width: 650,
        height: 35,
        z_index: 2,
        font_size: 15,
        font_weight: "bold",
        text_align: "center",
        vertical_align: "middle",
        color: "#c5a03f",
        overflow: "truncate",
        static_text: "Legendary Creature — Royal Knight",
        letter_spacing: 1,
      },
      // Decorative divider
      {
        id: "t5-11",
        type: "shape",
        x: 150,
        y: 595,
        width: 450,
        height: 2,
        z_index: 2,
        shape_type: "rectangle",
        fill_type: "linear",
        gradient: {
          type: "linear",
          angle: 90,
          stops: [
            { color: "rgba(197,160,63,0)", position: 0 },
            { color: "#c5a03f", position: 50 },
            { color: "rgba(197,160,63,0)", position: 100 },
          ],
        },
      },
      // Rules
      {
        id: "t5-12",
        type: "shape",
        x: 35,
        y: 610,
        width: 680,
        height: 330,
        z_index: 1,
        shape_type: "rectangle",
        fill: "rgba(17,2,32,0.6)",
        border_radius: 8,
        stroke: "rgba(197,160,63,0.2)",
        stroke_width: 1,
      },
      {
        id: "t5-13",
        type: "text",
        x: 55,
        y: 625,
        width: 640,
        height: 300,
        z_index: 2,
        font_size: 20,
        font_weight: "normal",
        text_align: "left",
        vertical_align: "top",
        color: "#ddd6fe",
        overflow: "wrap",
        static_text: "Rules text and abilities. Describe what this card does when it enters play, attacks, or is activated.",
      },
      // Power
      {
        id: "t5-14",
        type: "shape",
        x: 580,
        y: 958,
        width: 130,
        height: 52,
        z_index: 2,
        shape_type: "rectangle",
        fill: "#c5a03f",
        border_radius: 8,
        box_shadow: { color: "rgba(197,160,63,0.4)", offset_x: 0, offset_y: 2, blur: 10, spread: 0 },
      },
      {
        id: "t5-15",
        type: "text",
        x: 580,
        y: 958,
        width: 130,
        height: 52,
        z_index: 3,
        font_size: 26,
        font_weight: "bold",
        text_align: "center",
        vertical_align: "middle",
        color: "#1a0533",
        overflow: "truncate",
        static_text: "6 / 6",
      },
    ],
  },

  // ── Porcelain ──────────────────────────────────────────────
  {
    id: "porcelain",
    name: "Porcelain",
    description: "Elegant white with soft blue accents.",
    category: "General",
    width: 750,
    height: 1050,
    elements: [
      // White background
      {
        id: "t6-1",
        type: "shape",
        x: 0,
        y: 0,
        width: 750,
        height: 1050,
        z_index: 0,
        shape_type: "rectangle",
        fill: "#f8fafc",
      },
      // Soft blue accent stripe (top)
      {
        id: "t6-2",
        type: "shape",
        x: 0,
        y: 0,
        width: 750,
        height: 5,
        z_index: 3,
        shape_type: "rectangle",
        fill_type: "linear",
        gradient: {
          type: "linear",
          angle: 90,
          stops: [
            { color: "#3b82f6", position: 0 },
            { color: "#60a5fa", position: 50 },
            { color: "#93c5fd", position: 100 },
          ],
        },
      },
      // Title
      {
        id: "t6-3",
        type: "text",
        x: 50,
        y: 30,
        width: 540,
        height: 65,
        z_index: 2,
        font_size: 36,
        font_weight: "bold",
        text_align: "left",
        vertical_align: "middle",
        color: "#1e293b",
        overflow: "truncate",
        static_text: "Card Name",
      },
      // Cost circle
      {
        id: "t6-4",
        type: "shape",
        x: 640,
        y: 30,
        width: 65,
        height: 65,
        z_index: 2,
        shape_type: "ellipse",
        fill_type: "linear",
        gradient: {
          type: "linear",
          angle: 135,
          stops: [
            { color: "#3b82f6", position: 0 },
            { color: "#2563eb", position: 100 },
          ],
        },
        box_shadow: { color: "rgba(59,130,246,0.25)", offset_x: 0, offset_y: 2, blur: 8, spread: 0 },
      },
      {
        id: "t6-5",
        type: "text",
        x: 640,
        y: 30,
        width: 65,
        height: 65,
        z_index: 3,
        font_size: 28,
        font_weight: "bold",
        text_align: "center",
        vertical_align: "middle",
        color: "#ffffff",
        overflow: "truncate",
        static_text: "3",
      },
      // Divider
      {
        id: "t6-6",
        type: "shape",
        x: 50,
        y: 108,
        width: 650,
        height: 1,
        z_index: 1,
        shape_type: "rectangle",
        fill: "#e2e8f0",
      },
      // Art area
      {
        id: "t6-7",
        type: "shape",
        x: 40,
        y: 125,
        width: 670,
        height: 420,
        z_index: 1,
        shape_type: "rectangle",
        fill: "#e2e8f0",
        border_radius: 12,
      },
      {
        id: "t6-8",
        type: "image",
        x: 44,
        y: 129,
        width: 662,
        height: 412,
        z_index: 2,
        object_fit: "cover",
        border_radius: 10,
      },
      // Type line
      {
        id: "t6-9",
        type: "text",
        x: 50,
        y: 560,
        width: 650,
        height: 30,
        z_index: 2,
        font_size: 14,
        font_weight: "bold",
        text_align: "left",
        vertical_align: "middle",
        color: "#3b82f6",
        overflow: "truncate",
        static_text: "Creature — Water Spirit",
        letter_spacing: 1,
      },
      // Rules area
      {
        id: "t6-10",
        type: "shape",
        x: 40,
        y: 600,
        width: 670,
        height: 330,
        z_index: 1,
        shape_type: "rectangle",
        fill: "#f1f5f9",
        border_radius: 12,
      },
      {
        id: "t6-11",
        type: "text",
        x: 60,
        y: 620,
        width: 630,
        height: 290,
        z_index: 2,
        font_size: 20,
        font_weight: "normal",
        text_align: "left",
        vertical_align: "top",
        color: "#334155",
        overflow: "wrap",
        static_text: "Rules text and abilities. Describe what this card does, its interactions, and any special effects.",
      },
      // Stats pill
      {
        id: "t6-12",
        type: "shape",
        x: 540,
        y: 955,
        width: 170,
        height: 50,
        z_index: 2,
        shape_type: "rectangle",
        fill_type: "linear",
        gradient: {
          type: "linear",
          angle: 90,
          stops: [
            { color: "#3b82f6", position: 0 },
            { color: "#60a5fa", position: 100 },
          ],
        },
        border_radius: 25,
      },
      {
        id: "t6-13",
        type: "text",
        x: 540,
        y: 955,
        width: 170,
        height: 50,
        z_index: 3,
        font_size: 24,
        font_weight: "bold",
        text_align: "center",
        vertical_align: "middle",
        color: "#ffffff",
        overflow: "truncate",
        static_text: "4 / 3",
      },
    ],
  },

  // ── Bloom ──────────────────────────────────────────────────
  {
    id: "bloom",
    name: "Bloom",
    description: "Warm cream with coral and rose pink accents.",
    category: "General",
    width: 750,
    height: 1050,
    elements: [
      // Cream background
      {
        id: "t7-1",
        type: "shape",
        x: 0,
        y: 0,
        width: 750,
        height: 1050,
        z_index: 0,
        shape_type: "rectangle",
        fill: "#fef7f0",
      },
      // Rose accent glow (top)
      {
        id: "t7-2",
        type: "shape",
        x: 100,
        y: -100,
        width: 550,
        height: 350,
        z_index: 1,
        shape_type: "ellipse",
        fill_type: "radial",
        gradient: {
          type: "radial",
          stops: [
            { color: "rgba(251,113,133,0.12)", position: 0 },
            { color: "rgba(251,113,133,0)", position: 100 },
          ],
        },
      },
      // Title
      {
        id: "t7-3",
        type: "text",
        x: 50,
        y: 40,
        width: 550,
        height: 60,
        z_index: 2,
        font_size: 36,
        font_weight: "bold",
        text_align: "left",
        vertical_align: "middle",
        color: "#9f1239",
        overflow: "truncate",
        static_text: "Card Name",
      },
      // Cost badge
      {
        id: "t7-4",
        type: "shape",
        x: 635,
        y: 38,
        width: 70,
        height: 55,
        z_index: 2,
        shape_type: "rectangle",
        fill_type: "linear",
        gradient: {
          type: "linear",
          angle: 135,
          stops: [
            { color: "#fb7185", position: 0 },
            { color: "#e11d48", position: 100 },
          ],
        },
        border_radius: 10,
        box_shadow: { color: "rgba(225,29,72,0.2)", offset_x: 0, offset_y: 2, blur: 8, spread: 0 },
      },
      {
        id: "t7-5",
        type: "text",
        x: 635,
        y: 38,
        width: 70,
        height: 55,
        z_index: 3,
        font_size: 26,
        font_weight: "bold",
        text_align: "center",
        vertical_align: "middle",
        color: "#ffffff",
        overflow: "truncate",
        static_text: "2",
      },
      // Thin divider
      {
        id: "t7-6",
        type: "shape",
        x: 50,
        y: 112,
        width: 200,
        height: 2,
        z_index: 2,
        shape_type: "rectangle",
        fill_type: "linear",
        gradient: {
          type: "linear",
          angle: 90,
          stops: [
            { color: "#fb7185", position: 0 },
            { color: "rgba(251,113,133,0)", position: 100 },
          ],
        },
      },
      // Art area
      {
        id: "t7-7",
        type: "shape",
        x: 40,
        y: 130,
        width: 670,
        height: 420,
        z_index: 1,
        shape_type: "rectangle",
        fill: "#fce7f3",
        border_radius: 16,
      },
      {
        id: "t7-8",
        type: "image",
        x: 46,
        y: 136,
        width: 658,
        height: 408,
        z_index: 2,
        object_fit: "cover",
        border_radius: 12,
      },
      // Type line
      {
        id: "t7-9",
        type: "shape",
        x: 40,
        y: 565,
        width: 670,
        height: 38,
        z_index: 1,
        shape_type: "rectangle",
        fill_type: "linear",
        gradient: {
          type: "linear",
          angle: 90,
          stops: [
            { color: "#fce7f3", position: 0 },
            { color: "#fef7f0", position: 100 },
          ],
        },
        border_radius: 8,
      },
      {
        id: "t7-10",
        type: "text",
        x: 55,
        y: 568,
        width: 640,
        height: 32,
        z_index: 2,
        font_size: 14,
        font_weight: "bold",
        text_align: "left",
        vertical_align: "middle",
        color: "#be123c",
        overflow: "truncate",
        static_text: "Enchantment — Aura",
        letter_spacing: 1,
      },
      // Rules area
      {
        id: "t7-11",
        type: "shape",
        x: 40,
        y: 618,
        width: 670,
        height: 320,
        z_index: 1,
        shape_type: "rectangle",
        fill: "#fff5f5",
        border_radius: 12,
        stroke: "#fecdd3",
        stroke_width: 1,
      },
      {
        id: "t7-12",
        type: "text",
        x: 60,
        y: 636,
        width: 630,
        height: 284,
        z_index: 2,
        font_size: 20,
        font_weight: "normal",
        text_align: "left",
        vertical_align: "top",
        color: "#4c0519",
        overflow: "wrap",
        static_text: "Card text and abilities. This area holds rules, flavor text, and descriptions.",
      },
      // Footer accent
      {
        id: "t7-13",
        type: "text",
        x: 50,
        y: 968,
        width: 650,
        height: 35,
        z_index: 2,
        font_size: 14,
        font_weight: "normal",
        text_align: "right",
        vertical_align: "middle",
        color: "#e11d48",
        overflow: "truncate",
        static_text: "Collection Name",
      },
    ],
  },

  // ── Slate ──────────────────────────────────────────────────
  {
    id: "slate",
    name: "Slate",
    description: "Clean light gray with sharp orange accents.",
    category: "General",
    width: 750,
    height: 1050,
    elements: [
      // Light background
      {
        id: "t8-1",
        type: "shape",
        x: 0,
        y: 0,
        width: 750,
        height: 1050,
        z_index: 0,
        shape_type: "rectangle",
        fill: "#ffffff",
      },
      // Left accent bar
      {
        id: "t8-2",
        type: "shape",
        x: 0,
        y: 0,
        width: 6,
        height: 1050,
        z_index: 3,
        shape_type: "rectangle",
        fill_type: "linear",
        gradient: {
          type: "linear",
          angle: 180,
          stops: [
            { color: "#f97316", position: 0 },
            { color: "#ea580c", position: 50 },
            { color: "#f97316", position: 100 },
          ],
        },
      },
      // Header area
      {
        id: "t8-3",
        type: "shape",
        x: 0,
        y: 0,
        width: 750,
        height: 100,
        z_index: 1,
        shape_type: "rectangle",
        fill: "#f8fafc",
      },
      // Title
      {
        id: "t8-4",
        type: "text",
        x: 30,
        y: 25,
        width: 530,
        height: 55,
        z_index: 2,
        font_size: 34,
        font_weight: "bold",
        text_align: "left",
        vertical_align: "middle",
        color: "#0f172a",
        overflow: "truncate",
        static_text: "Card Name",
      },
      // Cost
      {
        id: "t8-5",
        type: "shape",
        x: 620,
        y: 25,
        width: 100,
        height: 50,
        z_index: 2,
        shape_type: "rectangle",
        fill: "#f97316",
        border_radius: 8,
      },
      {
        id: "t8-6",
        type: "text",
        x: 620,
        y: 25,
        width: 100,
        height: 50,
        z_index: 3,
        font_size: 24,
        font_weight: "bold",
        text_align: "center",
        vertical_align: "middle",
        color: "#ffffff",
        overflow: "truncate",
        static_text: "4",
      },
      // Type line under header
      {
        id: "t8-7",
        type: "text",
        x: 30,
        y: 78,
        width: 400,
        height: 20,
        z_index: 2,
        font_size: 12,
        font_weight: "bold",
        text_align: "left",
        vertical_align: "middle",
        color: "#f97316",
        overflow: "truncate",
        static_text: "ARTIFACT — EQUIPMENT",
        letter_spacing: 2,
      },
      // Divider
      {
        id: "t8-8",
        type: "shape",
        x: 0,
        y: 100,
        width: 750,
        height: 1,
        z_index: 2,
        shape_type: "rectangle",
        fill: "#e2e8f0",
      },
      // Art
      {
        id: "t8-9",
        type: "image",
        x: 30,
        y: 120,
        width: 690,
        height: 430,
        z_index: 1,
        object_fit: "cover",
        border_radius: 8,
      },
      // Rules section
      {
        id: "t8-10",
        type: "shape",
        x: 20,
        y: 570,
        width: 710,
        height: 370,
        z_index: 1,
        shape_type: "rectangle",
        fill: "#f8fafc",
        border_radius: 8,
      },
      {
        id: "t8-11",
        type: "text",
        x: 40,
        y: 590,
        width: 670,
        height: 330,
        z_index: 2,
        font_size: 20,
        font_weight: "normal",
        text_align: "left",
        vertical_align: "top",
        color: "#1e293b",
        overflow: "wrap",
        static_text: "Rules text and card effects. Describe abilities, costs, and interactions here.",
      },
      // Bottom divider
      {
        id: "t8-12",
        type: "shape",
        x: 0,
        y: 955,
        width: 750,
        height: 1,
        z_index: 2,
        shape_type: "rectangle",
        fill: "#e2e8f0",
      },
      // Stats row
      {
        id: "t8-13",
        type: "shape",
        x: 570,
        y: 970,
        width: 145,
        height: 48,
        z_index: 2,
        shape_type: "rectangle",
        fill: "#fff7ed",
        border_radius: 8,
        stroke: "#f97316",
        stroke_width: 2,
      },
      {
        id: "t8-14",
        type: "text",
        x: 570,
        y: 970,
        width: 145,
        height: 48,
        z_index: 3,
        font_size: 24,
        font_weight: "bold",
        text_align: "center",
        vertical_align: "middle",
        color: "#ea580c",
        overflow: "truncate",
        static_text: "3 / 5",
      },
    ],
  },

  // ── Chronicle ─────────────────────────────────────────────────
  // Circular image left, text stack right, parchment tones
  {
    id: "chronicle",
    name: "Chronicle",
    description: "Circular portrait with side-by-side text layout.",
    category: "General",
    width: 750,
    height: 1050,
    elements: [
      // Background
      {
        id: "t9-1",
        type: "shape",
        x: 0,
        y: 0,
        width: 750,
        height: 1050,
        z_index: 0,
        shape_type: "rectangle",
        fill: "#f5f0e8",
      },
      // Thin border
      {
        id: "t9-2",
        type: "shape",
        x: 15,
        y: 15,
        width: 720,
        height: 1020,
        z_index: 1,
        shape_type: "rectangle",
        fill: "transparent",
        stroke: "#c4a76c",
        border_radius: 12,
      },
      // Circular image
      {
        id: "t9-3",
        type: "image",
        x: 50,
        y: 100,
        width: 280,
        height: 280,
        z_index: 2,
        object_fit: "cover",
        border_radius: 140,
      },
      // Title
      {
        id: "t9-4",
        type: "text",
        x: 370,
        y: 115,
        width: 340,
        height: 55,
        z_index: 2,
        static_text: "Card Name",
        font_size: 34,
        font_weight: "bold",
        text_align: "left",
        vertical_align: "middle",
        color: "#3d2914",
        overflow: "truncate",
      },
      // Divider
      {
        id: "t9-5",
        type: "shape",
        x: 370,
        y: 180,
        width: 200,
        height: 2,
        z_index: 2,
        shape_type: "rectangle",
        fill: "#c4a76c",
      },
      // Type line
      {
        id: "t9-6",
        type: "text",
        x: 370,
        y: 195,
        width: 340,
        height: 25,
        z_index: 2,
        static_text: "Creature — Historian",
        font_size: 13,
        font_weight: "bold",
        text_align: "left",
        vertical_align: "middle",
        color: "#8b6914",
        overflow: "truncate",
        letter_spacing: 1,
      },
      // Side description
      {
        id: "t9-7",
        type: "text",
        x: 370,
        y: 235,
        width: 340,
        height: 140,
        z_index: 2,
        static_text:
          "A brief summary or flavor text for this card goes here.",
        font_size: 18,
        font_weight: "normal",
        text_align: "left",
        vertical_align: "top",
        color: "#5c4033",
        overflow: "wrap",
        line_height: 1.3,
      },
      // Rules box
      {
        id: "t9-8",
        type: "shape",
        x: 40,
        y: 430,
        width: 670,
        height: 360,
        z_index: 1,
        shape_type: "rectangle",
        fill: "#efe8d8",
        border_radius: 10,
      },
      // Rules text
      {
        id: "t9-9",
        type: "text",
        x: 60,
        y: 450,
        width: 630,
        height: 320,
        z_index: 2,
        static_text:
          "Rules text and abilities. Describe what this card does, its interactions, and special effects.",
        font_size: 20,
        font_weight: "normal",
        text_align: "left",
        vertical_align: "top",
        color: "#3d2914",
        overflow: "wrap",
        line_height: 1.3,
      },
      // Stats badge bg
      {
        id: "t9-10",
        type: "shape",
        x: 555,
        y: 940,
        width: 155,
        height: 50,
        z_index: 2,
        shape_type: "rectangle",
        fill: "#c4a76c",
        border_radius: 8,
      },
      // Stats text
      {
        id: "t9-11",
        type: "text",
        x: 555,
        y: 940,
        width: 155,
        height: 50,
        z_index: 3,
        static_text: "4 / 3",
        font_size: 24,
        font_weight: "bold",
        text_align: "center",
        vertical_align: "middle",
        color: "#3d2914",
        overflow: "truncate",
      },
      // Top accent bar
      {
        id: "t9-12",
        type: "shape",
        x: 0,
        y: 0,
        width: 750,
        height: 4,
        z_index: 3,
        shape_type: "rectangle",
        fill: "#c4a76c",
      },
    ],
  },

  // ── Prism ────────────────────────────────────────────────────────
  // Full-bleed image top with gradient fade, title overlaid
  {
    id: "prism",
    name: "Prism",
    description: "Full-bleed art with gradient fade to dark.",
    category: "General",
    width: 750,
    height: 1050,
    elements: [
      // Background
      {
        id: "t10-1",
        type: "shape",
        x: 0,
        y: 0,
        width: 750,
        height: 1050,
        z_index: 0,
        shape_type: "rectangle",
        fill: "#1a1a2e",
      },
      // Full-bleed image
      {
        id: "t10-2",
        type: "image",
        x: 0,
        y: 0,
        width: 750,
        height: 580,
        z_index: 1,
        object_fit: "cover",
      },
      // Gradient overlay
      {
        id: "t10-3",
        type: "shape",
        x: 0,
        y: 380,
        width: 750,
        height: 200,
        z_index: 2,
        shape_type: "rectangle",
        fill_type: "linear",
        gradient: {
          type: "linear",
          angle: 180,
          stops: [
            { color: "rgba(26,26,46,0)", position: 0 },
            { color: "#1a1a2e", position: 100 },
          ],
        },
      },
      // Title overlaid
      {
        id: "t10-4",
        type: "text",
        x: 50,
        y: 485,
        width: 650,
        height: 60,
        z_index: 3,
        static_text: "Card Name",
        font_size: 40,
        font_weight: "bold",
        text_align: "left",
        vertical_align: "middle",
        color: "#ffffff",
        overflow: "truncate",
        text_shadow: { color: "rgba(0,0,0,0.6)", offset_x: 0, offset_y: 2, blur: 8 },
      },
      // Type line
      {
        id: "t10-5",
        type: "text",
        x: 50,
        y: 555,
        width: 400,
        height: 25,
        z_index: 3,
        static_text: "SORCERY — ILLUSION",
        font_size: 13,
        font_weight: "bold",
        text_align: "left",
        vertical_align: "middle",
        color: "#a78bfa",
        overflow: "truncate",
        letter_spacing: 2,
      },
      // Rules box
      {
        id: "t10-6",
        type: "shape",
        x: 40,
        y: 600,
        width: 670,
        height: 330,
        z_index: 2,
        shape_type: "rectangle",
        fill: "rgba(255,255,255,0.05)",
        stroke: "rgba(255,255,255,0.1)",
        border_radius: 12,
      },
      // Rules text
      {
        id: "t10-7",
        type: "text",
        x: 60,
        y: 620,
        width: 630,
        height: 290,
        z_index: 3,
        static_text:
          "Rules text and abilities. Describe what this card does, its interactions, and special effects.",
        font_size: 20,
        font_weight: "normal",
        text_align: "left",
        vertical_align: "top",
        color: "#d1d5db",
        overflow: "wrap",
        line_height: 1.3,
      },
      // Stats pill bg
      {
        id: "t10-8",
        type: "shape",
        x: 540,
        y: 955,
        width: 170,
        height: 50,
        z_index: 3,
        shape_type: "rectangle",
        fill_type: "linear",
        gradient: {
          type: "linear",
          angle: 90,
          stops: [
            { color: "#7c3aed", position: 0 },
            { color: "#ec4899", position: 100 },
          ],
        },
        border_radius: 25,
      },
      // Stats text
      {
        id: "t10-9",
        type: "text",
        x: 540,
        y: 955,
        width: 170,
        height: 50,
        z_index: 4,
        static_text: "6 / 4",
        font_size: 24,
        font_weight: "bold",
        text_align: "center",
        vertical_align: "middle",
        color: "#ffffff",
        overflow: "truncate",
      },
      // Rainbow top bar
      {
        id: "t10-10",
        type: "shape",
        x: 0,
        y: 0,
        width: 750,
        height: 5,
        z_index: 4,
        shape_type: "rectangle",
        fill_type: "linear",
        gradient: {
          type: "linear",
          angle: 90,
          stops: [
            { color: "#ff0055", position: 0 },
            { color: "#ffaa00", position: 25 },
            { color: "#00cc88", position: 50 },
            { color: "#0088ff", position: 75 },
            { color: "#aa44ff", position: 100 },
          ],
        },
      },
    ],
  },

  // ── Midnight ─────────────────────────────────────────────────────
  // Rounded pill image top-center, centered text, navy/silver
  {
    id: "midnight",
    name: "Midnight",
    description: "Centered rounded art with moonlit navy tones.",
    category: "General",
    width: 750,
    height: 1050,
    elements: [
      // Background
      {
        id: "t11-1",
        type: "shape",
        x: 0,
        y: 0,
        width: 750,
        height: 1050,
        z_index: 0,
        shape_type: "rectangle",
        fill_type: "radial",
        gradient: {
          type: "radial",
          stops: [
            { color: "#0f1535", position: 0 },
            { color: "#0a0e27", position: 100 },
          ],
        },
      },
      // Glow halo
      {
        id: "t11-2",
        type: "shape",
        x: 175,
        y: -10,
        width: 400,
        height: 220,
        z_index: 1,
        shape_type: "ellipse",
        fill_type: "radial",
        gradient: {
          type: "radial",
          stops: [
            { color: "rgba(100,149,237,0.15)", position: 0 },
            { color: "rgba(100,149,237,0)", position: 100 },
          ],
        },
      },
      // Rounded image
      {
        id: "t11-3",
        type: "image",
        x: 175,
        y: 70,
        width: 400,
        height: 300,
        z_index: 2,
        object_fit: "cover",
        border_radius: 24,
      },
      // Title centered
      {
        id: "t11-4",
        type: "text",
        x: 50,
        y: 415,
        width: 650,
        height: 55,
        z_index: 2,
        static_text: "Card Name",
        font_size: 36,
        font_weight: "bold",
        text_align: "center",
        vertical_align: "middle",
        color: "#e2e8f0",
        overflow: "truncate",
        text_shadow: { color: "rgba(100,149,237,0.4)", offset_x: 0, offset_y: 0, blur: 12 },
      },
      // Type line centered
      {
        id: "t11-5",
        type: "text",
        x: 50,
        y: 478,
        width: 650,
        height: 25,
        z_index: 2,
        static_text: "Enchantment — Lunar",
        font_size: 13,
        font_weight: "bold",
        text_align: "center",
        vertical_align: "middle",
        color: "#6b7fa3",
        overflow: "truncate",
        letter_spacing: 2,
      },
      // Center divider
      {
        id: "t11-6",
        type: "shape",
        x: 275,
        y: 515,
        width: 200,
        height: 1,
        z_index: 2,
        shape_type: "rectangle",
        fill: "rgba(100,149,237,0.4)",
      },
      // Rules box
      {
        id: "t11-7",
        type: "shape",
        x: 40,
        y: 540,
        width: 670,
        height: 340,
        z_index: 1,
        shape_type: "rectangle",
        fill: "rgba(255,255,255,0.04)",
        stroke: "rgba(100,149,237,0.2)",
        border_radius: 12,
      },
      // Rules text
      {
        id: "t11-8",
        type: "text",
        x: 60,
        y: 560,
        width: 630,
        height: 300,
        z_index: 2,
        static_text:
          "Rules text and abilities. Describe what this card does, its interactions, and special effects.",
        font_size: 20,
        font_weight: "normal",
        text_align: "left",
        vertical_align: "top",
        color: "#94a3b8",
        overflow: "wrap",
        line_height: 1.3,
      },
      // Stats pill outline
      {
        id: "t11-9",
        type: "shape",
        x: 540,
        y: 920,
        width: 170,
        height: 50,
        z_index: 2,
        shape_type: "rectangle",
        fill: "transparent",
        stroke: "#6480b0",
        border_radius: 25,
      },
      // Stats text
      {
        id: "t11-10",
        type: "text",
        x: 540,
        y: 920,
        width: 170,
        height: 50,
        z_index: 3,
        static_text: "3 / 5",
        font_size: 24,
        font_weight: "bold",
        text_align: "center",
        vertical_align: "middle",
        color: "#c0c8d8",
        overflow: "truncate",
      },
      // Moon circle deco
      {
        id: "t11-11",
        type: "shape",
        x: 645,
        y: 30,
        width: 65,
        height: 65,
        z_index: 1,
        shape_type: "ellipse",
        fill_type: "radial",
        gradient: {
          type: "radial",
          stops: [
            { color: "rgba(200,220,255,0.15)", position: 0 },
            { color: "rgba(200,220,255,0)", position: 100 },
          ],
        },
      },
    ],
  },

  // ── Mosaic ───────────────────────────────────────────────────────
  // Two image slots side-by-side, teal/coral
  {
    id: "mosaic",
    name: "Mosaic",
    description: "Dual image slots with teal and coral accents.",
    category: "General",
    width: 750,
    height: 1050,
    elements: [
      // Background
      {
        id: "t12-1",
        type: "shape",
        x: 0,
        y: 0,
        width: 750,
        height: 1050,
        z_index: 0,
        shape_type: "rectangle",
        fill: "#0d1b2a",
      },
      // Left image
      {
        id: "t12-2",
        type: "image",
        x: 40,
        y: 50,
        width: 325,
        height: 380,
        z_index: 1,
        object_fit: "cover",
        border_radius: 12,
      },
      // Right image
      {
        id: "t12-3",
        type: "image",
        x: 385,
        y: 50,
        width: 325,
        height: 380,
        z_index: 1,
        object_fit: "cover",
        border_radius: 12,
      },
      // Title
      {
        id: "t12-4",
        type: "text",
        x: 50,
        y: 465,
        width: 650,
        height: 55,
        z_index: 2,
        static_text: "Card Name",
        font_size: 36,
        font_weight: "bold",
        text_align: "left",
        vertical_align: "middle",
        color: "#ff6b6b",
        overflow: "truncate",
      },
      // Type line
      {
        id: "t12-5",
        type: "text",
        x: 50,
        y: 528,
        width: 400,
        height: 25,
        z_index: 2,
        static_text: "ARTIFACT — DUAL CORE",
        font_size: 13,
        font_weight: "bold",
        text_align: "left",
        vertical_align: "middle",
        color: "#4ecdc4",
        overflow: "truncate",
        letter_spacing: 2,
      },
      // Divider
      {
        id: "t12-6",
        type: "shape",
        x: 50,
        y: 565,
        width: 300,
        height: 2,
        z_index: 2,
        shape_type: "rectangle",
        fill_type: "linear",
        gradient: {
          type: "linear",
          angle: 90,
          stops: [
            { color: "#ff6b6b", position: 0 },
            { color: "rgba(255,107,107,0)", position: 100 },
          ],
        },
      },
      // Rules box
      {
        id: "t12-7",
        type: "shape",
        x: 40,
        y: 585,
        width: 670,
        height: 320,
        z_index: 1,
        shape_type: "rectangle",
        fill: "rgba(255,255,255,0.04)",
        stroke: "rgba(78,205,196,0.2)",
        border_radius: 12,
      },
      // Rules text
      {
        id: "t12-8",
        type: "text",
        x: 60,
        y: 605,
        width: 630,
        height: 280,
        z_index: 2,
        static_text:
          "Rules text and abilities. Describe what this card does, its interactions, and special effects.",
        font_size: 20,
        font_weight: "normal",
        text_align: "left",
        vertical_align: "top",
        color: "#e2d8c0",
        overflow: "wrap",
        line_height: 1.3,
      },
      // Stats badge bg
      {
        id: "t12-9",
        type: "shape",
        x: 550,
        y: 940,
        width: 160,
        height: 50,
        z_index: 2,
        shape_type: "rectangle",
        fill: "#ff6b6b",
        border_radius: 8,
      },
      // Stats text
      {
        id: "t12-10",
        type: "text",
        x: 550,
        y: 940,
        width: 160,
        height: 50,
        z_index: 3,
        static_text: "5 / 5",
        font_size: 24,
        font_weight: "bold",
        text_align: "center",
        vertical_align: "middle",
        color: "#0d1b2a",
        overflow: "truncate",
      },
      // Coral top bar
      {
        id: "t12-11",
        type: "shape",
        x: 0,
        y: 0,
        width: 750,
        height: 4,
        z_index: 3,
        shape_type: "rectangle",
        fill: "#ff6b6b",
      },
    ],
  },

  // ── Sovereign ────────────────────────────────────────────────────
  // Image at bottom, title and text at top, burgundy/gold
  {
    id: "sovereign",
    name: "Sovereign",
    description: "Text-first layout with art at the bottom.",
    category: "General",
    width: 750,
    height: 1050,
    elements: [
      // Background
      {
        id: "t13-1",
        type: "shape",
        x: 0,
        y: 0,
        width: 750,
        height: 1050,
        z_index: 0,
        shape_type: "rectangle",
        fill_type: "linear",
        gradient: {
          type: "linear",
          angle: 180,
          stops: [
            { color: "#1a0505", position: 0 },
            { color: "#2d0a0a", position: 100 },
          ],
        },
      },
      // Gold border
      {
        id: "t13-2",
        type: "shape",
        x: 18,
        y: 18,
        width: 714,
        height: 1014,
        z_index: 1,
        shape_type: "rectangle",
        fill: "transparent",
        stroke: "#d4af37",
      },
      // Title
      {
        id: "t13-3",
        type: "text",
        x: 50,
        y: 45,
        width: 550,
        height: 65,
        z_index: 2,
        static_text: "Card Name",
        font_size: 40,
        font_weight: "bold",
        text_align: "left",
        vertical_align: "middle",
        color: "#d4af37",
        overflow: "truncate",
        text_shadow: { color: "rgba(212,175,55,0.3)", offset_x: 0, offset_y: 1, blur: 8 },
      },
      // Cost circle
      {
        id: "t13-4",
        type: "shape",
        x: 650,
        y: 48,
        width: 56,
        height: 56,
        z_index: 2,
        shape_type: "ellipse",
        fill: "#d4af37",
      },
      // Cost text
      {
        id: "t13-5",
        type: "text",
        x: 650,
        y: 48,
        width: 56,
        height: 56,
        z_index: 3,
        static_text: "7",
        font_size: 28,
        font_weight: "bold",
        text_align: "center",
        vertical_align: "middle",
        color: "#1a0505",
        overflow: "truncate",
      },
      // Type line
      {
        id: "t13-6",
        type: "text",
        x: 50,
        y: 125,
        width: 400,
        height: 25,
        z_index: 2,
        static_text: "LEGENDARY — SOVEREIGN",
        font_size: 13,
        font_weight: "bold",
        text_align: "left",
        vertical_align: "middle",
        color: "#b8860b",
        overflow: "truncate",
        letter_spacing: 2,
      },
      // Divider
      {
        id: "t13-7",
        type: "shape",
        x: 50,
        y: 162,
        width: 650,
        height: 1,
        z_index: 2,
        shape_type: "rectangle",
        fill: "rgba(212,175,55,0.3)",
      },
      // Rules text
      {
        id: "t13-8",
        type: "text",
        x: 50,
        y: 180,
        width: 650,
        height: 280,
        z_index: 2,
        static_text:
          "Rules text and abilities. Describe what this card does, its interactions, and special effects. This layout puts the text first so the reader sees abilities before the art.",
        font_size: 20,
        font_weight: "normal",
        text_align: "left",
        vertical_align: "top",
        color: "#e8c9a0",
        overflow: "wrap",
        line_height: 1.3,
      },
      // Stats row
      {
        id: "t13-9",
        type: "text",
        x: 50,
        y: 470,
        width: 650,
        height: 35,
        z_index: 2,
        static_text: "8 / 8",
        font_size: 22,
        font_weight: "bold",
        text_align: "right",
        vertical_align: "middle",
        color: "#d4af37",
        overflow: "truncate",
      },
      // Bottom image
      {
        id: "t13-10",
        type: "image",
        x: 30,
        y: 530,
        width: 690,
        height: 480,
        z_index: 1,
        object_fit: "cover",
        border_radius: 8,
      },
      // Gradient fade over top of image
      {
        id: "t13-11",
        type: "shape",
        x: 30,
        y: 530,
        width: 690,
        height: 80,
        z_index: 2,
        shape_type: "rectangle",
        fill_type: "linear",
        gradient: {
          type: "linear",
          angle: 180,
          stops: [
            { color: "rgba(45,10,10,0.7)", position: 0 },
            { color: "rgba(45,10,10,0)", position: 100 },
          ],
        },
        border_radius: 8,
      },
    ],
  },

  // ── Horizon ──────────────────────────────────────────────────────
  // Wide landscape image strip in middle, text above and below
  {
    id: "horizon",
    name: "Horizon",
    description: "Landscape art strip with clean emerald accents.",
    category: "General",
    width: 750,
    height: 1050,
    elements: [
      // Background
      {
        id: "t14-1",
        type: "shape",
        x: 0,
        y: 0,
        width: 750,
        height: 1050,
        z_index: 0,
        shape_type: "rectangle",
        fill: "#f8f6f3",
      },
      // Title
      {
        id: "t14-2",
        type: "text",
        x: 50,
        y: 40,
        width: 550,
        height: 60,
        z_index: 2,
        static_text: "Card Name",
        font_size: 36,
        font_weight: "bold",
        text_align: "left",
        vertical_align: "middle",
        color: "#1a1a1a",
        overflow: "truncate",
      },
      // Cost badge bg
      {
        id: "t14-3",
        type: "shape",
        x: 640,
        y: 38,
        width: 70,
        height: 50,
        z_index: 2,
        shape_type: "rectangle",
        fill: "#059669",
        border_radius: 10,
      },
      // Cost text
      {
        id: "t14-4",
        type: "text",
        x: 640,
        y: 38,
        width: 70,
        height: 50,
        z_index: 3,
        static_text: "2",
        font_size: 24,
        font_weight: "bold",
        text_align: "center",
        vertical_align: "middle",
        color: "#ffffff",
        overflow: "truncate",
      },
      // Type line
      {
        id: "t14-5",
        type: "text",
        x: 50,
        y: 110,
        width: 400,
        height: 22,
        z_index: 2,
        static_text: "INSTANT — NATURE",
        font_size: 12,
        font_weight: "bold",
        text_align: "left",
        vertical_align: "middle",
        color: "#059669",
        overflow: "truncate",
        letter_spacing: 2,
      },
      // Top divider
      {
        id: "t14-6",
        type: "shape",
        x: 50,
        y: 148,
        width: 650,
        height: 1,
        z_index: 2,
        shape_type: "rectangle",
        fill: "#d1d5db",
      },
      // Landscape image strip
      {
        id: "t14-7",
        type: "image",
        x: 0,
        y: 170,
        width: 750,
        height: 340,
        z_index: 1,
        object_fit: "cover",
      },
      // Bottom fade on image
      {
        id: "t14-8",
        type: "shape",
        x: 0,
        y: 430,
        width: 750,
        height: 80,
        z_index: 2,
        shape_type: "rectangle",
        fill_type: "linear",
        gradient: {
          type: "linear",
          angle: 180,
          stops: [
            { color: "rgba(248,246,243,0)", position: 0 },
            { color: "#f8f6f3", position: 100 },
          ],
        },
      },
      // Rules box
      {
        id: "t14-9",
        type: "shape",
        x: 40,
        y: 530,
        width: 670,
        height: 340,
        z_index: 1,
        shape_type: "rectangle",
        fill: "#f0ede8",
        border_radius: 12,
      },
      // Rules text
      {
        id: "t14-10",
        type: "text",
        x: 60,
        y: 550,
        width: 630,
        height: 300,
        z_index: 2,
        static_text:
          "Rules text and abilities. Describe what this card does, its interactions, and special effects.",
        font_size: 20,
        font_weight: "normal",
        text_align: "left",
        vertical_align: "top",
        color: "#374151",
        overflow: "wrap",
        line_height: 1.3,
      },
      // Stats pill outline
      {
        id: "t14-11",
        type: "shape",
        x: 550,
        y: 910,
        width: 160,
        height: 45,
        z_index: 2,
        shape_type: "rectangle",
        fill: "transparent",
        stroke: "#059669",
        border_radius: 22,
      },
      // Stats text
      {
        id: "t14-12",
        type: "text",
        x: 550,
        y: 910,
        width: 160,
        height: 45,
        z_index: 3,
        static_text: "2 / 4",
        font_size: 22,
        font_weight: "bold",
        text_align: "center",
        vertical_align: "middle",
        color: "#059669",
        overflow: "truncate",
      },
      // Bottom emerald bar
      {
        id: "t14-13",
        type: "shape",
        x: 0,
        y: 1046,
        width: 750,
        height: 4,
        z_index: 3,
        shape_type: "rectangle",
        fill: "#059669",
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════
  // Yu-Gi-Oh Templates (813×1185)
  // ═══════════════════════════════════════════════════════════════════

  // ── Normal Monster ───────────────────────────────────────────────
  {
    id: "ygo-normal",
    name: "Normal Monster",
    description: "Yellow frame for vanilla monsters.",
    category: "Yu-Gi-Oh",
    width: 813,
    height: 1185,
    elements: [
      {
        id: "ygo1-bg",
        type: "image",
        x: 0,
        y: 0,
        width: 813,
        height: 1185,
        z_index: 0,
        static_src: "/images/templates/yu-gi-oh/normal.png",
        object_fit: "fill",
      },
      {
        id: "ygo1-name",
        type: "text",
        x: 50,
        y: 32,
        width: 580,
        height: 52,
        z_index: 1,
        static_text: "Card Name",
        font_size: 36,
        font_weight: "bold",
        text_align: "left",
        vertical_align: "middle",
        color: "#000000",
        overflow: "truncate",
      },
      {
        id: "ygo1-desc",
        type: "text",
        x: 55,
        y: 830,
        width: 700,
        height: 210,
        z_index: 1,
        static_text: "Card description / flavor text goes here.",
        font_size: 20,
        font_weight: "normal",
        text_align: "left",
        vertical_align: "top",
        color: "#000000",
        overflow: "wrap",
        line_height: 1.3,
      },
      {
        id: "ygo1-atk",
        type: "text",
        x: 455,
        y: 1098,
        width: 130,
        height: 40,
        z_index: 1,
        static_text: "ATK/0000",
        font_size: 24,
        font_weight: "bold",
        text_align: "right",
        vertical_align: "middle",
        color: "#000000",
        overflow: "truncate",
      },
      {
        id: "ygo1-def",
        type: "text",
        x: 615,
        y: 1098,
        width: 140,
        height: 40,
        z_index: 1,
        static_text: "DEF/0000",
        font_size: 24,
        font_weight: "bold",
        text_align: "right",
        vertical_align: "middle",
        color: "#000000",
        overflow: "truncate",
      },
    ],
  },

  // ── Effect Monster ───────────────────────────────────────────────
  {
    id: "ygo-effect",
    name: "Effect Monster",
    description: "Orange frame for effect monsters.",
    category: "Yu-Gi-Oh",
    width: 813,
    height: 1185,
    elements: [
      {
        id: "ygo2-bg",
        type: "image",
        x: 0,
        y: 0,
        width: 813,
        height: 1185,
        z_index: 0,
        static_src: "/images/templates/yu-gi-oh/effect.png",
        object_fit: "fill",
      },
      {
        id: "ygo2-name",
        type: "text",
        x: 50,
        y: 32,
        width: 580,
        height: 52,
        z_index: 1,
        static_text: "Card Name",
        font_size: 36,
        font_weight: "bold",
        text_align: "left",
        vertical_align: "middle",
        color: "#000000",
        overflow: "truncate",
      },
      {
        id: "ygo2-desc",
        type: "text",
        x: 55,
        y: 830,
        width: 700,
        height: 210,
        z_index: 1,
        static_text: "Effect description goes here.",
        font_size: 20,
        font_weight: "normal",
        text_align: "left",
        vertical_align: "top",
        color: "#000000",
        overflow: "wrap",
        line_height: 1.3,
      },
      {
        id: "ygo2-atk",
        type: "text",
        x: 455,
        y: 1098,
        width: 130,
        height: 40,
        z_index: 1,
        static_text: "ATK/0000",
        font_size: 24,
        font_weight: "bold",
        text_align: "right",
        vertical_align: "middle",
        color: "#000000",
        overflow: "truncate",
      },
      {
        id: "ygo2-def",
        type: "text",
        x: 615,
        y: 1098,
        width: 140,
        height: 40,
        z_index: 1,
        static_text: "DEF/0000",
        font_size: 24,
        font_weight: "bold",
        text_align: "right",
        vertical_align: "middle",
        color: "#000000",
        overflow: "truncate",
      },
    ],
  },

  // ── Ritual Monster ───────────────────────────────────────────────
  {
    id: "ygo-ritual",
    name: "Ritual Monster",
    description: "Blue frame for ritual monsters.",
    category: "Yu-Gi-Oh",
    width: 813,
    height: 1185,
    elements: [
      {
        id: "ygo3-bg",
        type: "image",
        x: 0,
        y: 0,
        width: 813,
        height: 1185,
        z_index: 0,
        static_src: "/images/templates/yu-gi-oh/ritual.png",
        object_fit: "fill",
      },
      {
        id: "ygo3-name",
        type: "text",
        x: 50,
        y: 32,
        width: 580,
        height: 52,
        z_index: 1,
        static_text: "Card Name",
        font_size: 36,
        font_weight: "bold",
        text_align: "left",
        vertical_align: "middle",
        color: "#000000",
        overflow: "truncate",
      },
      {
        id: "ygo3-desc",
        type: "text",
        x: 55,
        y: 830,
        width: 700,
        height: 210,
        z_index: 1,
        static_text: "Ritual effect description goes here.",
        font_size: 20,
        font_weight: "normal",
        text_align: "left",
        vertical_align: "top",
        color: "#000000",
        overflow: "wrap",
        line_height: 1.3,
      },
      {
        id: "ygo3-atk",
        type: "text",
        x: 455,
        y: 1098,
        width: 130,
        height: 40,
        z_index: 1,
        static_text: "ATK/0000",
        font_size: 24,
        font_weight: "bold",
        text_align: "right",
        vertical_align: "middle",
        color: "#000000",
        overflow: "truncate",
      },
      {
        id: "ygo3-def",
        type: "text",
        x: 615,
        y: 1098,
        width: 140,
        height: 40,
        z_index: 1,
        static_text: "DEF/0000",
        font_size: 24,
        font_weight: "bold",
        text_align: "right",
        vertical_align: "middle",
        color: "#000000",
        overflow: "truncate",
      },
    ],
  },

  // ── Synchro Monster ──────────────────────────────────────────────
  {
    id: "ygo-synchro",
    name: "Synchro Monster",
    description: "White frame for synchro monsters.",
    category: "Yu-Gi-Oh",
    width: 813,
    height: 1185,
    elements: [
      {
        id: "ygo4-bg",
        type: "image",
        x: 0,
        y: 0,
        width: 813,
        height: 1185,
        z_index: 0,
        static_src: "/images/templates/yu-gi-oh/synchro.png",
        object_fit: "fill",
      },
      {
        id: "ygo4-name",
        type: "text",
        x: 50,
        y: 32,
        width: 580,
        height: 52,
        z_index: 1,
        static_text: "Card Name",
        font_size: 36,
        font_weight: "bold",
        text_align: "left",
        vertical_align: "middle",
        color: "#000000",
        overflow: "truncate",
      },
      {
        id: "ygo4-desc",
        type: "text",
        x: 55,
        y: 830,
        width: 700,
        height: 210,
        z_index: 1,
        static_text: "Synchro effect description goes here.",
        font_size: 20,
        font_weight: "normal",
        text_align: "left",
        vertical_align: "top",
        color: "#000000",
        overflow: "wrap",
        line_height: 1.3,
      },
      {
        id: "ygo4-atk",
        type: "text",
        x: 455,
        y: 1098,
        width: 130,
        height: 40,
        z_index: 1,
        static_text: "ATK/0000",
        font_size: 24,
        font_weight: "bold",
        text_align: "right",
        vertical_align: "middle",
        color: "#000000",
        overflow: "truncate",
      },
      {
        id: "ygo4-def",
        type: "text",
        x: 615,
        y: 1098,
        width: 140,
        height: 40,
        z_index: 1,
        static_text: "DEF/0000",
        font_size: 24,
        font_weight: "bold",
        text_align: "right",
        vertical_align: "middle",
        color: "#000000",
        overflow: "truncate",
      },
    ],
  },

  // ── XYZ Monster ──────────────────────────────────────────────────
  {
    id: "ygo-xyz",
    name: "XYZ Monster",
    description: "Black frame for XYZ monsters.",
    category: "Yu-Gi-Oh",
    width: 813,
    height: 1185,
    elements: [
      {
        id: "ygo5-bg",
        type: "image",
        x: 0,
        y: 0,
        width: 813,
        height: 1185,
        z_index: 0,
        static_src: "/images/templates/yu-gi-oh/xyz.png",
        object_fit: "fill",
      },
      {
        id: "ygo5-name",
        type: "text",
        x: 50,
        y: 32,
        width: 580,
        height: 52,
        z_index: 1,
        static_text: "Card Name",
        font_size: 36,
        font_weight: "bold",
        text_align: "left",
        vertical_align: "middle",
        color: "#ffffff",
        overflow: "truncate",
      },
      {
        id: "ygo5-desc",
        type: "text",
        x: 55,
        y: 830,
        width: 700,
        height: 210,
        z_index: 1,
        static_text: "XYZ effect description goes here.",
        font_size: 20,
        font_weight: "normal",
        text_align: "left",
        vertical_align: "top",
        color: "#000000",
        overflow: "wrap",
        line_height: 1.3,
      },
      {
        id: "ygo5-atk",
        type: "text",
        x: 455,
        y: 1098,
        width: 130,
        height: 40,
        z_index: 1,
        static_text: "ATK/0000",
        font_size: 24,
        font_weight: "bold",
        text_align: "right",
        vertical_align: "middle",
        color: "#000000",
        overflow: "truncate",
      },
      {
        id: "ygo5-def",
        type: "text",
        x: 615,
        y: 1098,
        width: 140,
        height: 40,
        z_index: 1,
        static_text: "DEF/0000",
        font_size: 24,
        font_weight: "bold",
        text_align: "right",
        vertical_align: "middle",
        color: "#000000",
        overflow: "truncate",
      },
    ],
  },

  // ── Link Monster ─────────────────────────────────────────────────
  {
    id: "ygo-link",
    name: "Link Monster",
    description: "Blue hexagonal frame for link monsters.",
    category: "Yu-Gi-Oh",
    width: 813,
    height: 1185,
    elements: [
      {
        id: "ygo6-bg",
        type: "image",
        x: 0,
        y: 0,
        width: 813,
        height: 1185,
        z_index: 0,
        static_src: "/images/templates/yu-gi-oh/link.png",
        object_fit: "fill",
      },
      {
        id: "ygo6-name",
        type: "text",
        x: 50,
        y: 32,
        width: 580,
        height: 52,
        z_index: 1,
        static_text: "Card Name",
        font_size: 36,
        font_weight: "bold",
        text_align: "left",
        vertical_align: "middle",
        color: "#ffffff",
        overflow: "truncate",
      },
      {
        id: "ygo6-desc",
        type: "text",
        x: 55,
        y: 830,
        width: 700,
        height: 210,
        z_index: 1,
        static_text: "Link effect description goes here.",
        font_size: 20,
        font_weight: "normal",
        text_align: "left",
        vertical_align: "top",
        color: "#000000",
        overflow: "wrap",
        line_height: 1.3,
      },
      {
        id: "ygo6-atk",
        type: "text",
        x: 455,
        y: 1098,
        width: 130,
        height: 40,
        z_index: 1,
        static_text: "ATK/0000",
        font_size: 24,
        font_weight: "bold",
        text_align: "right",
        vertical_align: "middle",
        color: "#000000",
        overflow: "truncate",
      },
      {
        id: "ygo6-link",
        type: "text",
        x: 615,
        y: 1098,
        width: 140,
        height: 40,
        z_index: 1,
        static_text: "LINK-2",
        font_size: 24,
        font_weight: "bold",
        text_align: "right",
        vertical_align: "middle",
        color: "#000000",
        overflow: "truncate",
      },
    ],
  },

  // ── Spell Card ───────────────────────────────────────────────────
  {
    id: "ygo-spell",
    name: "Spell Card",
    description: "Green frame for spell cards.",
    category: "Yu-Gi-Oh",
    width: 813,
    height: 1185,
    elements: [
      {
        id: "ygo7-bg",
        type: "image",
        x: 0,
        y: 0,
        width: 813,
        height: 1185,
        z_index: 0,
        static_src: "/images/templates/yu-gi-oh/spell.png",
        object_fit: "fill",
      },
      {
        id: "ygo7-name",
        type: "text",
        x: 50,
        y: 32,
        width: 580,
        height: 52,
        z_index: 1,
        static_text: "Card Name",
        font_size: 36,
        font_weight: "bold",
        text_align: "left",
        vertical_align: "middle",
        color: "#000000",
        overflow: "truncate",
      },
      {
        id: "ygo7-icon",
        type: "image",
        x: 700,
        y: 28,
        width: 76,
        height: 76,
        z_index: 1,
        static_src: "/images/templates/yu-gi-oh/spell-icon.png",
        object_fit: "contain",
      },
      {
        id: "ygo7-desc",
        type: "text",
        x: 55,
        y: 830,
        width: 700,
        height: 270,
        z_index: 1,
        static_text: "Spell effect description goes here.",
        font_size: 20,
        font_weight: "normal",
        text_align: "left",
        vertical_align: "top",
        color: "#000000",
        overflow: "wrap",
        line_height: 1.3,
      },
    ],
  },

  // ── Trap Card ────────────────────────────────────────────────────
  {
    id: "ygo-trap",
    name: "Trap Card",
    description: "Purple frame for trap cards.",
    category: "Yu-Gi-Oh",
    width: 813,
    height: 1185,
    elements: [
      {
        id: "ygo8-bg",
        type: "image",
        x: 0,
        y: 0,
        width: 813,
        height: 1185,
        z_index: 0,
        static_src: "/images/templates/yu-gi-oh/trap.png",
        object_fit: "fill",
      },
      {
        id: "ygo8-name",
        type: "text",
        x: 50,
        y: 32,
        width: 580,
        height: 52,
        z_index: 1,
        static_text: "Card Name",
        font_size: 36,
        font_weight: "bold",
        text_align: "left",
        vertical_align: "middle",
        color: "#000000",
        overflow: "truncate",
      },
      {
        id: "ygo8-desc",
        type: "text",
        x: 55,
        y: 830,
        width: 700,
        height: 270,
        z_index: 1,
        static_text: "Trap effect description goes here.",
        font_size: 20,
        font_weight: "normal",
        text_align: "left",
        vertical_align: "top",
        color: "#000000",
        overflow: "wrap",
        line_height: 1.3,
      },
    ],
  },
];
